# Generated by Django 5.2.7 on 2025-10-13 23:14

import inventario.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serial', models.CharField(help_text='Identificador único del equipo.', max_length=150, unique=True, verbose_name='Número de Serie / Etiqueta de Activo')),
                ('localizacion', models.CharField(max_length=150, verbose_name='Localización / Ubicación Física')),
                ('descripcion', models.TextField(blank=True, verbose_name='Especificaciones / Notas')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Adquisición')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=inventario.utils.limpiar_nombre_archivo, verbose_name='Foto del Elemento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Elemento de Inventario',
                'verbose_name_plural': 'Elementos de Inventario',
                'ordering': ['tipo_dispositivo', 'marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='EstadoElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Estado')),
            ],
            options={
                'verbose_name': 'Estado del Elemento',
                'verbose_name_plural': 'Estados de Elementos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Dispositivo')),
            ],
            options={
                'verbose_name': 'Tipo de Dispositivo',
                'verbose_name_plural': 'Tipos de Dispositivos',
                'ordering': ['nombre'],
            },
        ),
    ]
