# Generated by Django 5.2.7 on 2025-10-13 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='usuario_registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventario.estadoelemento', verbose_name='Estado Actual'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='tipo_dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipodispositivo', verbose_name='Tipo de Dispositivo'),
        ),
    ]
