# Generated by Django 5.2.7 on 2025-12-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de unidades disponibles (solo si no tiene serial único).', verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='maneja_cantidad',
            field=models.BooleanField(default=False, help_text='Marcar si este elemento se controla por cantidad (ej: cables, mouse) en lugar de serial único.', verbose_name='¿Maneja Cantidad?'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='serial',
            field=models.CharField(blank=True, help_text='Identificador único del equipo (opcional si maneja cantidad).', max_length=150, null=True, unique=True, verbose_name='Número de Serie / Etiqueta de Activo'),
        ),
    ]
