# Generated by Django 5.2.7 on 2025-10-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_apellido_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha sido aprobado por un administrador para acceder al sistema.', verbose_name='Usuario Aprobado'),
        ),
    ]
